const film = [
  {
    id: 1,
    img : "/Movies-img/1.jpg",
    name: "The Shawshank Redemption",
    genre: "Drama",
    director: "Frank Darabont",
    rating: 9.3,
  },
  {
    id: 2,
    img : "/Movies-img/2.jpg",
    name: "The Godfather",
    genre: "Crime, Drama",
    director: "Francis Ford Coppola",
    rating: 9.2,
  },
  {
    id: 3,
    img : "/Movies-img/3.jpg",
    name: "The Godfather: Part II",
    genre: "Crime, Drama",
    director: "Francis Ford Coppola",
    rating: 9.0,
  },
  {
    id: 4,
    img : "/Movies-img/4.jpg",
    name: "The Dark Knight",
    genre: "Action, Crime, Drama",
    director: "Christopher Nolan",
    rating: 9.0,
  },
  {
    id: 5,
    img : "/Movies-img/5.jpg",
    name: "12 Angry Men",
    genre: "Drama",
    director: "Sidney Lumet",
    rating: 8.9,
  },
  {
    id: 6,
    img : "/Movies-img/6.jpg",
    name: "Schindler's List",
    genre: "Biography, Drama, History",
    director: "Steven Spielberg",
    rating: 8.9,
  },
  {
    id: 7,
    img : "/Movies-img/7.jpg",
    name: "Pulp Fiction",
    genre: "Crime, Drama",
    director: "Quentin Tarantino",
    rating: 8.9,
  },
  {
    id: 8,
    img : "/Movies-img/8.jpg",
    name: "The Lord of the Rings: The Return of the King",
    genre: "Adventure, Drama, Fantasy",
    director: "Peter Jackson",
    rating: 8.9,
  },
  {
    id: 9,
    img : "/Movies-img/9.jpg",
    name: "The Good, the Bad and the Ugly",
    genre: "Western",
    director: "Sergio Leone",
    rating: 8.9,
  },
  {
    id: 10,
    img : "/Movies-img/10.jpg",
    name: "Fight Club",
    genre: "Drama",
    director: "David Fincher",
    rating: 8.8,
  },
];

export default film;
